#스프링 부트 서버가 실행되면 자동으로 로딩
spring:
  jpa:
    show-sql: true #전송 쿼리 확인
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true #테이블 생성 후에 data.sql 실행
  datasource:
    url: jdbc:h2:mem:testdb
  h2:
    console:
      enabled: true

springdoc:
  swagger-ui: # swagger
    path: /api-test  # swagger-ui 접근 경로에 대한 별칭, 해당 주소로 접속해도 http://localhost:8080/swagger-ui/index.html로 리다이렉션 됨.

    groups-order: DESC # path, query, body, response 순으로 출력

    tags-sorter: alpha # 태그를 알파벳 순으로 정렬

    operations-sorter: method  # delete - get - patch - post - put 순으로 정렬, alpha를 사용하면 알파벳 순으로 정렬 가능

  paths-to-match:
    - /api/** # swagger-ui에 표시할 api의 엔드포인트 패턴